### PR TITLE
fix(api, init, add, profile menu): More fixes and refactoring

### LINKED ISSUE #168: bug: User can open their profile app, then click “current dataset”, both menus will be open
need to close profile menu when not focused

### LINKED ISSUE #194: Show meta by default on create/add dataset

### LINKED ISSUE #206: Bug: if dataset returns with error, clear selection
This requires catching the error in `fetchWorkingDataset`

### PR DESCRIPTION
**Pull request by ramfox**
closes #206  
closes #194
closes #168

### CODE REVIEW

File: app/actions/api.ts [hunk 1]
```diff
@@ -169,7 +171,18 @@ export function fetchWorkingDataset (): ApiActionThunk {
       }
     }
 
-    return dispatch(action)
+    const result = (dispatch(action) as unknown) as Promise<AnyAction>
```
Comment (b5) [inline app/actions/api.ts]: Add a comment here explaining what's going on:
```js
// the action being dispatched will be intercepted by api middleware and return a promise
// typescript requires we first cast to unknown to drop the stated return type of the dispatch function
const result = (dispatch(action) as unknown) as Promise<AnyAction>
```

File: app/actions/api.ts [hunk 2]
```diff
@@ -169,7 +171,18 @@ export function fetchWorkingDataset (): ApiActionThunk {
...
+    return new Promise((resolve, reject) => {
+      result.then(action => {
+        if (getActionType(action) === 'failure') {
+          if (action.payload.err.code === 404 || action.payload.err.code === 500) {
+            dispatch(clearSelection())
```
Comment (b5) [inline app/actions/api.ts]: add a comment here explaining what's happening:
```js
// if the working dataset isn't found, we have dataset selection that no longer exists. clear the selection.
dispatch(clearSelection())
```

File: app/actions/api.ts [hunk 3]
```diff
@@ -441,6 +454,12 @@ export function addDatasetAndFetch (peername: string, name: string): ApiActionTh
     try {
       response = await addDataset(peername, name)(dispatch, getState)
       response = await whenOk(fetchMyDatasets())(response)
+      const action = response as ApiResponseAction
+      const { data } = action.payload
```
Comment (b5) [inline app/actions/api.ts]: If we're not using a default value for data (because we _know_ data will be present), there's no need for this destructuring.

Refactor to just:
```js
const { isLinked, published } = action.payload.data.find((dataset: DatasetSummary) => dataset.name === name && dataset.peername === peername)
```

File: app/actions/api.ts [hunk 4]
```diff
@@ -475,6 +494,12 @@ export function initDatasetAndFetch (sourcebodypath: string, name: string, dir:
     try {
       response = await initDataset(sourcebodypath, name, dir, mkdir)(dispatch, getState)
       response = await whenOk(fetchMyDatasets())(response)
+      const action = response as ApiResponseAction
+      const { data } = action.payload
```
Comment (b5) [inline app/actions/api.ts]: Same as above, no need to destructure `data`

File: app/components/chrome/HeaderColumnButtonDropdown.tsx [hunk 5]
```diff
@@ -12,10 +12,30 @@ const HeaderColumnButtonDropdown: React.FunctionComponent<HeaderColumnButtonDrop
...
+    if (dropdown.current !== null && dropdown.current.contains(e.target)) {
+      // inside click
+      return
+    }
+    // outside click
+    setShowMenu(false)
+  }
+
+  React.useEffect(() => {
+    document.addEventListener('mousedown', (e) => handleClick(e))
```
Comment (b5) [inline app/components/chrome/HeaderColumnButtonDropdown.tsx]: any reason not to use the [`click` event](https://caniuse.com/#search=click%20event) instead of `mousedown`? mousedown has funny implications: if you click and hold, it'll fire the action right away.

File: app/store/api.ts [hunk 6]
```diff
@@ -56,6 +56,18 @@ interface ApiQuery {
...
 }
 
+interface ApiError {
+  code: number
+  message?: string
+}
+
+export interface ApiResponseAction {
+  type: string
+  payload: {
```
Comment (b5) [inline app/store/api.ts]: consider refactoring to:
```ts
payload: Record<string,any>
```

This will require `payload` be an object with no functions.

File: app/store/api.ts [hunk 7]
```diff
@@ -56,6 +56,18 @@ interface ApiQuery {
   [key: string]: string
 }
 
+interface ApiError {
```
Comment (b5) [inline app/store/api.ts]: pretend this is go. Let's get a comment defining the struct, a comment on `code` clarifying that it'll be an HTTP response code, and a comment on message "error message returned from qri"

File: app/store/api.ts [hunk 8]
```diff
@@ -56,6 +56,18 @@ interface ApiQuery {
...
+  code: number
+  message?: string
+}
+
+export interface ApiResponseAction {
```
Comment (b5) [inline app/store/api.ts]: ditto to linting requirements:
```ts
// ApiResponseActions are emitted as side effects by api middleware. They come in "success" and "error" variations
export ApiResponseAction
```

File: app/components/chrome/HeaderColumnButtonDropdown.tsx (hunk 5 above)
Comment (ramfox) [reply app/components/chrome/HeaderColumnButtonDropdown.tsx]: no reason, adjusting now

**Comment by ramfox** [comment]
Your review made me realize I haven't been doing my duty in commenting code! Resolving to have better commenting habits.
